# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField()),
                ('begin_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(null=True)),
                ('search_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='parent_uuid',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
